import Footer from "./Footer";
import Header from "./Header";
import Head from "next/head";

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>TAM Creates</title>
				<meta
					name="description"
					content="Generated by TAM (Tarique Ali Mirza <tarique1988@gmail.com>)"
				/>
				<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
			</Head>
			<div className="flex flex-col justify-between min-h-screen">
				<Header />
				{children}
				<Footer />
			</div>
		</>
	);
};

export default Layout;
